version: '3.9'

services:
  db:
    build:
      context: ./docker-context/db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - /Users/woohyeon/personal-project/work_space/nuber-eats-backend/db-data:/var/lib/postgresql/data
